### ISSUE TITLE
OpenLayers  vs Leaflet

### ISSUE THREAD

**Issue by erikthysell** [finnjordal/dafkort#1]
Kortforsyrningens eksempel benyttede Leaflet. Er der en særlig anledning til at jeres eksempel benytter OpenLayers?

**Comment by finnjordal** [comment]
Beklager det sene svar.
Baggrunden for at vælge OpenLayers fremfor Leaflet er dels at OpenLayers er mere anvendt; dels at community'et omkring OpenLayers er mere aktivt

**Comment by erikthysell** [comment]
OK, mange tak for svar. For mig at se lader til at det er helt [omvent](https://stackshare.io/stackups/leaflet-vs-openlayers).. 
Jeg har brugt leaflet og er meget tilfredse med det, især for det er relativt "light".

**Comment by finnjordal** [comment]
Min kilde til aktiviteten omkring udviklingen af de to JavaScript kort framework er GitHub. Sidste release for [Leaflet ](https://github.com/Leaflet/Leaflet) er d. 4. september 2020 (22 releases). For [OpenLayers ](https://github.com/openlayers/openlayers) er det d. 29. december 2021 (103 releases).
Jeg vil give dig ret i, at Leaflet kan være mere attraktiv at anvende for udviklere uden den store GIS viden. ET andet problem med Leaflet i forhold til korttjenester fra SDFE er at SDFE's korttjenester anvender koordinatsystemet ETRS89 / UTM zone 32 Nord og at Leaflet anvender WGS84 / Geografiske koordinater, som betyder at man som udvikler skal forholde sig til to forskellige koordinatsystemer.
Det er baggrunden for at vælge OpenLayers i kodeeksemplerne.
Hvilke kodeksempler i Leaflet har du behov for? Hvilke af Datafordelerens korttjenster ønsker du at anvende? Er du i gang med et nyt projekt? Eller har du en eksisterende applikation, som skal have udskiftet Kortforsyningens korttjenester med Datafordelerens?
