### ISSUE TITLE
Opdatere package-lock.json

### ISSUE THREAD

**Issue by erikthysell** [finnjordal/dafkort#2]
> The package-lock.json file was created with an old version of npm
... -> opdatering af package-lock.json ville være ønskværdigt ..

**Comment by finnjordal** [comment]
Beklager det sene svar.
Vi opdatere ikke eksemplerne for hver ny version af værktøjerne der anvendes i eksemplerne.
Alle eksemplerne er udviklet som Open Source, så pull requests er meget velkomne.
